
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Comedy Prague
email: comedy.prague@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Comedy Prague - bringing you regular standup comedy shows in Prague since 2013!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://comedyprague.cz" # the base hostname & protocol for your site, e.g. http://example.com

comedians:
  - { id: luke-ryan, name: Luke Ryan }
  - { id: scott-lee-hansen, name: Scott Lee Hansen }
  - { id: kiro-nushev, name: Kiro Nushev }
  - { id: lucie-machackova, name: Lucie Macháčková }
  - { id: phil-micallef, name: Phil Micallef }
  - { id: katarina-puskarov, name: Katarina Puskarov }
  - { id: david-thompson, name: David Thompson }
  - { id: sean-riordain, name: Sean Ríordáin }
  - { id: lukas-stejskal, name: Lukáš Stejskal }
  - { id: bryan-flanagan, name: Bryan Flanagan }
  - { id: carmine-rodi-falanga, name: Carmine Rodi Falanga }
  - { id: spela-kopac, name: Špela Kopač }
  - { id: jeffrey-mons, name: Jeffrey Mons }
  - { id: alex, name: Alex }
  - { id: david-cox, name: David Cox }
  - { id: russell-adam-webb, name: Russell Adam Webb }
  - { id: willard-toydog, name: Willard }
  - { id: jeff-baugh, name: Jeff Baugh }

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
